baseURL = "https://links.giovstechs.it"
languageCode = "en"
defaultContentLanguage = "en"

title = "Links.GiovsTechs.dev"
copyright = "&#169; Copyright GiovsTechs.dev"
theme = 'lynx'
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Links.GiovsTechs.dev"
  headline = "A young developer of 15 years old."
  image = "img/pic.jpg"  

  links = [
    { email = "https://gvts.me/em" },
    { link = "https://gvts.me/" },
    { discord = "https://gvts.me/ds" },
    { github = "https://gvts.me/gh" },
    { gitlab = "https://gvts.me/gl" },
    { mastodon = "https://gvts.me/ms" },
    { telegram = "https://gvts.me/mtg" },
    { youtube = "https://gvts.me/yt" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
